chore: add storybook, basic story and documentation example
slnz/go pull request #1
Opened 2022-07-04 23:35 UTC by storyworks

Currently I've created only a basic IonWrapper which wraps pages in <IonApp>. 
We may later discover a need for an IconPageWrapper which also includes <IonPage> for smaller components.

I've modified the default introduction but kept it just as an example for how to write documentation

2022-07-04 23:36 UTC, storyworks commented on .storybook/preview.js
> +import React from 'react';
Configuration derived from https://dev.to/aaronksaunders/how-to-use-storybook-with-ionic-and-reactjs-57f3 and https://github.com/ionic-team/ionic-framework/issues/25409

2022-07-04 23:38 UTC, storyworks commented on package.json
> +    "eslint-plugin-n": "^15.2.4",
Only this import was added manually, storybook threw an error since eslint-config-standard depended on it but it was never imported

2022-07-05 03:10 UTC, tataihono requested changes
can you do ts main and preview?

2022-07-05 03:10 UTC, tataihono commented on .eslintrc.js
> +    'plugin:prettier/recommended',
prettier has to come last

2022-07-05 03:11 UTC, storyworks commented
> can you do ts main and preview?

Can try but it's .js in core

2022-07-05 04:08 UTC, storyworks commented on .storybook/main.ts
> +// Imports the Storybook's configuration API
Derived from https://storybook.js.org/docs/react/configure/overview#using-storybook-api and https://github.com/storybookjs/storybook/issues/17589

2022-07-05 04:09 UTC, storyworks commented on tsconfig.json
> +  "ts-node": {
To fix typescript issue with storybook main

2022-07-05 08:30 UTC, tataihono approved these changes

2022-07-05 21:02 UTC, merged