feat: add contact
slnz/go pull request #18
Opened 2022-07-27 23:06 UTC by edmonday

[Basecamp Link](https://3.basecamp.com/3105655/buckets/28313680/todos/5094599057)

- add contact form
- add contact form to add contact button
- navigate to person detail page on contact creation
- positioned add contact button on people list

2022-07-28 02:36 UTC, tataihono commented
@edmonday can you merge this in?

2022-07-28 23:10 UTC, tataihono requested changes

2022-07-28 23:10 UTC, tataihono commented on src/lib/queries/getContact/getContact.ts
> +      select: ['firstName', 'lastName', 'phoneNumbers', 'emails', 'realms']
is this needed?

2022-07-28 23:10 UTC, tataihono commented on src/lib/queries/getProcessDefinitions.handlers.ts
> +import { rest, RestHandler } from 'msw'
these getProcessDefinition files need to be delete

2022-07-28 23:10 UTC, tataihono commented on src/pages/PeoplePage/PersonAddPage/PersonAddPage.stories.tsx
> +import { Story, Meta } from '@storybook/react'
these pages need to be moved to pages/PersonAddPage

2022-07-28 23:23 UTC, tataihono requested changes

2022-07-28 23:23 UTC, tataihono commented on src/components/AddContact/AddContact.spec.tsx
> +import { QueryClient, QueryClientProvider } from 'react-query'
```suggestion
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
```

2022-07-28 23:23 UTC, tataihono commented on src/components/AddContact/AddContact.tsx
> +import { useMutation } from 'react-query'
```suggestion
import { useMutation } from '@tanstack/react-query'
```

2022-07-28 23:23 UTC, tataihono commented on src/components/AddContactButton/AddContactButton.spec.tsx
> +import { QueryClient, QueryClientProvider } from 'react-query'
```suggestion
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
```

2022-07-28 23:23 UTC, tataihono commented on src/components/ContactForm/ContactForm.spec.tsx
> +import { QueryClient, QueryClientProvider } from 'react-query'
```suggestion
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
```

2022-07-28 23:23 UTC, tataihono commented on src/lib/mutations/createContact.ts
> +import { MutationFunction } from 'react-query'
```suggestion
import { MutationFunction } from '@tanstack/react-query'
```

2022-07-28 23:25 UTC, edmonday commented on src/@types/fluro.d.ts
> +
True, I'll drop this.

2022-07-29 00:47 UTC, edmonday commented
@tataihono made the changes after your review

2022-07-29 01:25 UTC, edmonday commented
@tataihono  tests have been fixed, just waiting on the pending UI Tests

2022-07-29 01:34 UTC, tataihono requested changes

2022-07-29 01:34 UTC, tataihono commented on package.json
> -    "date-fns": "^2.28.0",
oh. this should not be removed.

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContact/AddContact.stories.tsx
> +import { userEvent, within, screen } from '@storybook/testing-library'
```suggestion
import { userEvent, within } from '@storybook/testing-library'
```

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContact/AddContact.tsx
> +    </>
```suggestion
      <ContactForm submitLabel="Add Contact" onSubmit={onSubmit} />
```

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContact/AddContact.spec.tsx
> +    render(
make use of `renderWithProviders` method so you don't need to provide the query client or the snack bar provider.

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContactButton/AddContactButton.stories.tsx
> +  const { getByRole, findByRole } = within(canvasElement)
```suggestion
  const { getByRole } = within(canvasElement)
```

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContact/AddContact.tsx
> +import { useMutation } from '@tanstack/react-query'
can this component be merged into the AddContactButton component?

2022-07-29 01:34 UTC, tataihono commented on src/components/AddContactButton/AddContactButton.spec.tsx
>      render(
renderWithProviders

2022-07-29 01:34 UTC, tataihono commented on src/components/ContactForm/ContactForm.spec.tsx
> +describe('AddContact', () => {
```suggestion
describe('ContactForm', () => {
```

2022-07-29 01:34 UTC, tataihono commented on src/components/ContactForm/ContactForm.spec.tsx
> +    render(
renderWithProviders

2022-07-29 01:34 UTC, tataihono commented on src/components/ContactForm/ContactForm.spec.tsx
> +    render(
renderWithProviders

2022-07-29 01:34 UTC, tataihono commented on src/components/ContactForm/ContactForm.spec.tsx
> +  render(
renderWithProviders

2022-07-29 01:34 UTC, tataihono commented on src/lib/queries/getProcessesQuery.ts
> +import { client } from '../fluro'
drop this file.

2022-07-29 03:35 UTC, edmonday commented
@tataihono changes have been made.

2022-07-29 04:45 UTC, tataihono approved these changes

2022-07-29 04:54 UTC, merged